#!/bin/bash
cd /afs/cern.ch/user/a/afkiaras/rucio-clients/public
source rucio/bin/activate

export X509_USER_PROXY=/afs/cern.ch/user/a/afkiaras/proxies/x509_escape
rm /afs/cern.ch/user/a/afkiaras/autogenerated/auto_uploaded_*
rses[0]="DESY-DCACHE"
rses[1]="LAPP-DCACHE"
rses[2]="ALPAMED-DPM"
rses[3]="IN2P3-CC-DCACHE"
rses[4]="SARA-DCACHE"
rses[5]="INFN-NA-DPM"
rses[6]="CNAF-STORM"
rses[7]="PIC-DCACHE"
rses[8]="EULAKE-1"
rses[9]="EULAKE-2"

upload_and_transfer () {
    len=${#rses[@]}
    for (( i=0; i<$len; i++ )); do
        RANDOM_STRING=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
        filename=/afs/cern.ch/user/a/afkiaras/autogenerated/auto_uploaded_$RANDOM_STRING
        did=auto_uploaded_$RANDOM_STRING
        echo $filename
        RANDOM_CONTENT=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
        truncate -s 10M $filename
        if [ $1 != $i ]; then
	    rucio upload --rse ${rses[$1]} --scope noise_4 $filename || return '1' #continue
            rucio add-rule noise_4:$did 1 ${rses[$i]};
	fi
        rm $filename
    done
}

upload_and_transfer 0
upload_and_transfer 1
upload_and_transfer 2
upload_and_transfer 3
upload_and_transfer 4
upload_and_transfer 5
upload_and_transfer 6
upload_and_transfer 7
upload_and_transfer 8
upload_and_transfer 9